import React from 'react';
import { Eye, Plus } from 'lucide-react';
import AuditInformation from './AuditInformation';

// ── Shared InfoRow ────────────────────────────────────────────────────────────

const InfoRow = ({ label, children, mono, last }) => (
  <div
    style={{
      display: 'grid',
      gridTemplateColumns: '160px 1fr',
      gap: '8px',
      alignItems: 'center',
      minHeight: '36px',
      borderBottom: last ? 'none' : '1px solid var(--color-border)',
    }}
  >
    <span style={{ fontSize: '13px', color: '#6b7280', fontWeight: 400, lineHeight: '1.4' }}>
      {label}
    </span>
    <span
      style={{
        fontSize: '13px',
        color: '#111827',
        fontWeight: 400,
        lineHeight: '1.4',
        fontFamily: mono ? 'monospace' : 'inherit',
        wordBreak: 'break-all',
      }}
    >
      {children ?? '-'}
    </span>
  </div>
);

// ── Status pill ───────────────────────────────────────────────────────────────

const StatusPill = ({ status }) => {
  const isActive = status?.toLowerCase() === 'active';
  return (
    <span
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        padding: '1px 9px',
        borderRadius: '20px',
        fontSize: '11px',
        fontWeight: 600,
        backgroundColor: isActive ? '#dcfce7' : '#fef9c3',
        color: isActive ? '#15803d' : '#854d0e',
      }}
    >
      <span
        style={{
          width: '5px',
          height: '5px',
          borderRadius: '50%',
          backgroundColor: isActive ? '#22c55e' : '#eab308',
          display: 'inline-block',
          flexShrink: 0,
        }}
      />
      {status || '-'}
    </span>
  );
};

// ── Section card ─────────────────────────────────────────────────────────────

const Section = ({ title, children }) => (
  <div
    style={{
      backgroundColor: 'white',
      border: '1px solid var(--color-border)',
      borderRadius: '8px',
      overflow: 'hidden',
    }}
  >
    <div style={{ padding: '14px 18px 10px' }}>
      <span style={{ fontSize: '12px', fontWeight: 500, color: 'var(--color-text-secondary)' }}>
        {title}
      </span>
    </div>
    <div style={{ padding: '0 18px' }}>{children}</div>
  </div>
);

// ── Widget card (matches existing widget-card style) ──────────────────────────

const WidgetCard = ({ title, value, sub }) => (
  <div className="widget-card" style={{ flex: 1 }}>
    <div className="widget-header">
      <h3 className="widget-title" style={{ margin: 0 }}>{title}</h3>
    </div>
    <div className="widget-value-row">
      <div className="widget-value" style={{ fontFamily: 'monospace', fontSize: '18px' }}>{value}</div>
    </div>
    {sub && <div className="widget-subtext text-gray">{sub}</div>}
  </div>
);

// ── Main component ────────────────────────────────────────────────────────────

const PaymentItemPage = ({ payment }) => {
  if (!payment) return null;

  // Derive values from payment row data; fall back to sample
  const accountNo   = payment.accountNo   || '3965738';
  const bank        = payment.bank        || 'Commercial Bank';
  const totalValue  = payment.value       || 'LKR 600,000,000.00';
  const startDate   = payment.startDate   || '2025-05-29';
  const duration    = payment.duration    || '5 years';

  // Static mock data (would typically come from API)
  const productType   = 'Long Term Loan';
  const branch        = 'Head Office Branch';
  const company       = 'Lion Brewery Sri Lanka';
  const currency      = 'Sri Lankan Rupee (LKR)';
  const currentRate   = '10%';
  const status        = 'Active';
  const totalPaid     = 'LKR 80,000,000.00';
  const remaining     = 'LKR 520,000,000.00';

  const paymentHistory = [
    { date: '2026-01-25', amount: 'LKR 10,000,000.00', note: '—', confirmedBy: 'Oshan Ruberu', confirmedAt: '2026-02-05 05:24' },
    { date: '2025-12-25', amount: 'LKR 10,000,000.00', note: 'Auto-generated by daily loan payment scheduler on 2025-12-29 03:00:01', confirmedBy: '', confirmedAt: '2025-12-29 03:00' },
    { date: '2025-11-25', amount: 'LKR 10,000,000.00', note: '—', confirmedBy: 'Oshan Ruberu', confirmedAt: '2025-11-30 12:14' },
    { date: '2025-10-29', amount: 'LKR 10,000,000.00', note: '—', confirmedBy: 'Oshan Ruberu', confirmedAt: '2025-11-30 12:14' },
  ];

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        flex: 1,
        height: '100%',
        overflowY: 'auto',
        backgroundColor: 'white',
        padding: '24px',
      }}
    >
      <style>{`
        .payment-detail-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 12px;
        }
        @media (max-width: 900px) {
          .payment-detail-grid { grid-template-columns: 1fr; }
        }
      `}</style>

      {/* ── Header (grey bg) ── */}
      <div
        style={{
          backgroundColor: 'var(--color-bg-subtle)',
          margin: '-24px -24px 28px -24px',
          padding: '20px 24px 24px',
          borderBottom: '1px solid var(--color-border)',
        }}
      >
        {/* Title + actions */}
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '20px' }}>
          <div>
            <h1 style={{ fontSize: '20px', fontWeight: 600, color: 'var(--color-text-main)', margin: 0 }}>
              Account Details
            </h1>
            <div style={{ marginTop: '3px', fontSize: '12px', color: 'var(--color-text-secondary)', fontFamily: 'monospace' }}>
              {accountNo}
            </div>
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="btn btn-outline" style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13px' }}>
              <Eye size={14} />
              View Account Master
            </button>
            <button className="btn btn-primary" style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13px' }}>
              <Plus size={14} />
              Record Payment
            </button>
          </div>
        </div>

        {/* ── Summary Widget Cards ── */}
        <div style={{ display: 'flex', gap: '16px' }}>
          <WidgetCard title="Total Loan Value"    value={totalValue} />
          <WidgetCard title="Total Paid"          value={totalPaid} />
          <WidgetCard title="Remaining Balance"   value={remaining} />
        </div>
      </div>

      {/* ── Account Information Detail Cards ── */}
      <div className="payment-detail-grid">
        <Section title="Account Information">
          <InfoRow label="Account Number" mono>{accountNo}</InfoRow>
          <InfoRow label="Product Type">{productType}</InfoRow>
          <InfoRow label="Bank">{bank}</InfoRow>
          <InfoRow label="Branch">{branch}</InfoRow>
          <InfoRow label="Company">{company}</InfoRow>
          <InfoRow label="Currency" last>{currency}</InfoRow>
        </Section>

        <Section title="Loan Details">
          <InfoRow label="Total Value" mono>{totalValue}</InfoRow>
          <InfoRow label="Start Date">{startDate}</InfoRow>
          <InfoRow label="Duration">{duration}</InfoRow>
          <InfoRow label="Current Rate">{currentRate}</InfoRow>
          <InfoRow label="Status" last>
            <StatusPill status={status} />
          </InfoRow>
        </Section>

        <Section title="Repayment Summary">
          <InfoRow label="Total Paid" mono>{totalPaid}</InfoRow>
          <InfoRow label="Remaining Balance" mono>{remaining}</InfoRow>
          <InfoRow label="Payments Made">8</InfoRow>
          <InfoRow label="Next Payment Due">2026-02-25</InfoRow>
          <InfoRow label="Next Payment Amt" mono last>LKR 10,000,000.00</InfoRow>
        </Section>
      </div>

      {/* ── Payment History Table ── */}
      <div style={{ marginTop: '32px' }}>
        <div style={{ marginBottom: '12px' }}>
          <h2 style={{ fontSize: '15px', fontWeight: 600, color: 'var(--color-text-main)', margin: 0 }}>
            Payment History
          </h2>
          <p style={{ fontSize: '12px', color: 'var(--color-text-secondary)', marginTop: '3px', marginBottom: 0 }}>
            All recorded payments for this account
          </p>
        </div>

        <div
          className="table-wrapper"
          style={{ margin: 0, backgroundColor: 'white', borderTop: '1px solid var(--color-border)' }}
        >
          <table className="data-table" style={{ borderCollapse: 'collapse', width: '100%' }}>
            <thead style={{ position: 'sticky', top: 0, zIndex: 10 }}>
              <tr>
                <th style={{ whiteSpace: 'nowrap' }}>PAYMENT DATE</th>
                <th style={{ whiteSpace: 'nowrap' }}>AMOUNT</th>
                <th style={{ whiteSpace: 'nowrap' }}>INTERNAL NOTE</th>
                <th style={{ whiteSpace: 'nowrap' }}>CONFIRMED BY</th>
                <th style={{ whiteSpace: 'nowrap' }}>CONFIRMED AT</th>
                <th style={{ whiteSpace: 'nowrap', textAlign: 'center' }}>ACTIONS</th>
              </tr>
            </thead>
            <tbody>
              {paymentHistory.map((row, idx) => (
                <tr key={idx} className="hover-row">
                  <td style={{ whiteSpace: 'nowrap', fontWeight: 500 }}>
                    {row.date}
                  </td>
                  <td style={{ whiteSpace: 'nowrap', fontFamily: 'monospace', color: '#16a34a', fontWeight: 600 }}>
                    {row.amount}
                  </td>
                  <td style={{ color: '#6b7280', fontSize: '12px', maxWidth: '280px', whiteSpace: 'normal', lineHeight: '1.4' }}>
                    {row.note}
                  </td>
                  <td style={{ whiteSpace: 'nowrap', color: 'var(--color-text-main)' }}>
                    {row.confirmedBy || '-'}
                  </td>
                  <td style={{ whiteSpace: 'nowrap', fontFamily: 'monospace', fontSize: '12px', color: '#6b7280' }}>
                    {row.confirmedAt}
                  </td>
                  <td style={{ textAlign: 'center', whiteSpace: 'nowrap' }}>
                    <button
                      className="control-icon"
                      title="Edit"
                      style={{ display: 'inline-flex', color: '#3b82f6' }}
                      onClick={(e) => e.stopPropagation()}
                    >
                      {/* pencil svg */}
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
                        <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
                      </svg>
                    </button>
                    <button
                      className="control-icon"
                      title="Delete"
                      style={{ display: 'inline-flex', color: '#ef4444' }}
                      onClick={(e) => e.stopPropagation()}
                    >
                      {/* trash svg */}
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <polyline points="3 6 5 6 21 6"/>
                        <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/>
                        <path d="M10 11v6"/><path d="M14 11v6"/>
                        <path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/>
                      </svg>
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* ── Audit Information ── */}
      <AuditInformation />

      <div style={{ height: '48px' }} />
    </div>
  );
};

export default PaymentItemPage;
