import React from 'react';
import ModulePage from '../ModulePage';

const Reports = () => {
  return (
    <ModulePage 
      title="Reports"
      columns={['Report Name', 'Type', 'Generated By', 'Date', 'Status']}
      data={[]}
      filterFields={['Type', 'Generated By', 'Status']}
      dataMap={{ 
          'Report Name': 'name', 
          'Type': 'type', 
          'Generated By': 'generatedBy',
          'Date': 'date',
          'Status': 'status' 
      }}
    />
  );
};

export default Reports;
